# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  client_id:
    description: The registered client_id
    type: string
  client_secret:
    description: The registered client_secret
    type: string
  provider:
    default: generic
    description: |
      The provider name, must be one of the following:
      ["generic", "google", "facebook", "microsoft", "github",
      "apple", "gitlab", "auth0", "slack", "spotify", "discord",
      "twitch", "netid", "yandex", "vkontakte", "dingtalk"].
      Defaults to "generic"
    type: string
  requested_claims:
    type: string
    description: |
      A JSON object containing lists of Claims being requested from each interface (userinfo, id_token).
      See https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter for more details.
  issuer_url:
    description: |
      The issuer_url, this value is only used when provider is "generic" or "auth0"
      type: string
    type: string
  microsoft_tenant_id:
    description: The Microsoft tenant_id. To be used only with microsoft providers.
    type: string
  apple_team_id:
    description: The Team ID provided by Apple. To be used only with apple providers.
    type: string
  apple_private_key_id:
    description: The private key identifier generated by Apple. To be used only with apple providers.
    type: string
  apple_private_key:
    description: The private key downloaded from Apple. To be used only with apple providers.
    type: string
